/****** Object:  Database [APIDemo]    Script Date: 11/09/2019 20:20:39 ******/
CREATE DATABASE [APIDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'APIDemo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\APIDemo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'APIDemo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\APIDemo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [APIDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [APIDemo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [APIDemo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [APIDemo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [APIDemo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [APIDemo] SET ARITHABORT OFF 
GO

ALTER DATABASE [APIDemo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [APIDemo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [APIDemo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [APIDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [APIDemo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [APIDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [APIDemo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [APIDemo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [APIDemo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [APIDemo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [APIDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [APIDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [APIDemo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [APIDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [APIDemo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [APIDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [APIDemo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [APIDemo] SET RECOVERY FULL 
GO

ALTER DATABASE [APIDemo] SET  MULTI_USER 
GO

ALTER DATABASE [APIDemo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [APIDemo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [APIDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [APIDemo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [APIDemo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [APIDemo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [APIDemo] SET  READ_WRITE 
GO

CREATE TABLE [APIDemo].[dbo].[Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [APIDemo].[dbo].[RefOrderStatus](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](250) NOT NULL,
 CONSTRAINT [PK_RefOrderStatus] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [APIDemo].[dbo].[Order](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[OrderStatusId] [int] NOT NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [APIDemo].[dbo].[Order]  WITH CHECK ADD FOREIGN KEY([CustomerId])
REFERENCES [APIDemo].[dbo].[Customer] ([Id])
GO

ALTER TABLE [APIDemo].[dbo].[Order]  WITH CHECK ADD FOREIGN KEY([OrderStatusId])
REFERENCES [APIDemo].[dbo].[RefOrderStatus] ([Id])
GO

